# Generated by Django 4.2 on 2023-04-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomoto', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='')),
                ('number', models.IntegerField(max_length=25)),
                ('wheels', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
